services:
  build_triedb:
    image: monad-execution-builder:latest
    command: monad_mpt --storage /dev/triedb --create
    volumes:
      - ./node:/monad
    devices:
      - /dev/triedb:/dev/triedb
    security_opt:
      - "seccomp:${MONAD_BFT_ROOT}/docker/devnet/monad/config/profile.json"
    ulimits:
      nofile:
        soft: 16384
        hard: 16384

  build_genesis:
    image: monad-execution-builder:latest
    depends_on:
      build_triedb:
        condition: service_completed_successfully
    volumes:
      - ./node:/monad
    devices:
      - /dev/triedb:/dev/triedb
    security_opt:
      - "seccomp:${MONAD_BFT_ROOT}/docker/devnet/monad/config/profile.json"
    command:
      monad
      --chain monad_devnet
      --db /dev/triedb
      --block_db /monad/ledger
      --nblocks 0
      --log_level ERROR
    ulimits:
      memlock:
        soft: "16770785280"
        hard: "16770785280"
      nofile:
        soft: 16384
        hard: 16384

  monad_execution:
    image: monad-execution-builder:latest
    depends_on:
      build_triedb:
        condition: service_completed_successfully
      build_genesis:
        condition: service_completed_successfully
    volumes:
      - ./node:/monad
      - sockets-volume:/sockets
    devices:
      - /dev/triedb:/dev/triedb
    security_opt:
      - "seccomp:${MONAD_BFT_ROOT}/docker/devnet/monad/config/profile.json"
    command: |
      monad
      --chain monad_devnet
      --db /dev/triedb
      --block_db /monad/ledger
      --statesync /sockets/statesync.sock
      --log_level ERROR
    ulimits:
      memlock:
        soft: "16770785280"
        hard: "16770785280"
      nofile:
        soft: 16384
        hard: 16384

  monad_node:
    build:
      context: ${MONAD_BFT_ROOT}
      dockerfile: ${DEVNET_DIR}/Dockerfile
      args:
        GIT_TAG_VERSION: ${GIT_TAG_VERSION}
    image: monad-node:latest
    depends_on:
      - build_triedb
      - monad_execution
    environment:
      - RUST_LOG=
    volumes:
      - ./node:/monad
      - sockets-volume:/sockets
    devices:
      - /dev/triedb:/dev/triedb
    security_opt:
      - "seccomp:${MONAD_BFT_ROOT}/docker/devnet/monad/config/profile.json"
    command: |
      monad-node
      --secp-identity /monad/config/id-secp
      --bls-identity /monad/config/id-bls
      --node-config /monad/config/node.toml
      --forkpoint-config /monad/config/forkpoint.genesis.toml
      --validators-path /monad/config/validators.toml
      --statesync-ipc-path /sockets/statesync.sock
      --wal-path /monad/wal
      --mempool-ipc-path /sockets/mempool.sock
      --control-panel-ipc-path /sockets/controlpanel.sock
      --ledger-path /monad/ledger
      --triedb-path /dev/triedb
    ulimits:
      memlock:
        soft: "16770785280"
        hard: "16770785280"
      nofile:
        soft: 16384
        hard: 16384

  monad_rpc:
    build:
      context: ${MONAD_BFT_ROOT}
      dockerfile: ${RPC_DIR}/Dockerfile
      args:
        GIT_TAG_VERSION: ${GIT_TAG_VERSION}
    image: monad-rpc:latest
    depends_on:
      - build_triedb
      - monad_node
    volumes:
      - ./node:/monad
      - sockets-volume:/sockets
    devices:
      - /dev/triedb:/dev/triedb
    security_opt:
      - "seccomp:${MONAD_BFT_ROOT}/docker/devnet/monad/config/profile.json"
    ports:
      - "8080:8080"
    command: |
      monad-rpc
      --ipc-path /sockets/mempool.sock
      --triedb-path /dev/triedb
      --node-config /monad/config/node.toml
      --allow-unprotected-txs
    ulimits:
      memlock:
        soft: "16770785280"
        hard: "16770785280"
      nofile:
        soft: 16384
        hard: 16384

networks:
  default:
    driver: bridge

volumes:
  sockets-volume:
